This notebook contains code to create and update an SQLite database containing MEA model parameters.

# Final run parameters

In [1]:
import sqlite3
import pandas as pd
#import mdbread

In [2]:
ss_strings = ['default_base',
              'default_clean',
              'default_woodbuilding',
              'low_base',
              'low_clean',
              'low_woodbuilding',
              'hi_base',
              'hi_clean',
              'hi_woodbuilding']
scenario_strings = ['FM_C', 'FM_A&C']
colmap = {'Sawnwood':'sawnwood',
          'Panel':'panels',
          'OtherIRW':'otherirw',
          'PulpPaper':'pulppaper',
          'BioenergyCommodities':'bioenergycommodities',
          'BioenergyHarvest':'bioenergyharvest',
          'BioenergyHarvestResidue':'bioenergyharvestresidue',
          'BioenergyMillResidue':'bioenergymillresidue',
          'tsa_num':'tsa_num'}

In [3]:
mea2_db_path = '../dat/mea_params/mea_params.db'
mea2_cnn = sqlite3.connect(mea2_db_path)

In [4]:
update_path = '../dat/mea_params_update'

## Production conversion parameters

The final runs will use distinct production conversion parameter matrices (`prodconv` table) for different combinations of _scenario suite_ and _scenario_. Each of these matrices was originally compiled by ZX in separate spreadsheets (9 scenario suites and 2 scenarios, total 18 matrices). Loop through all of these spreadsheets and import the results into the `prodconv` table.

In [5]:
mea2_cnn.execute("drop table prodconv")

In [6]:
i = 1
for s1 in ss_strings:
    for s2 in scenario_strings:
        print(s1, s2, i)
        filename = '%s/ConversionParameters_%s_future_%s.xls' % (update_path, s1, s2)
        df = pd.read_excel(filename, sheet_name='ConversionValues')
        df = df.drop(columns='FMU_ID').rename(columns=colmap)
        df['assumption_id'] = i
        df.to_sql('prodconv', mea2_cnn, if_exists='append', index=False)
        i += 1

default_base FM_C 1
default_base FM_A&C 2
default_clean FM_C 3
default_clean FM_A&C 4
default_woodbuilding FM_C 5
default_woodbuilding FM_A&C 6
low_base FM_C 7
low_base FM_A&C 8
low_clean FM_C 9
low_clean FM_A&C 10
low_woodbuilding FM_C 11
low_woodbuilding FM_A&C 12
hi_base FM_C 13
hi_base FM_A&C 14
hi_clean FM_C 15
hi_clean FM_A&C 16
hi_woodbuilding FM_C 17
hi_woodbuilding FM_A&C 18


In [7]:
df = pd.read_sql_query('select * from prodconv', mea2_cnn)
df

sawnwood    panels  otherirw  pulppaper  bioenergycommodities  \
0    2.352997  2.352997  2.352997   4.496488              2.352997   
1    2.361085  2.361085  2.361085   4.511943              2.361085   
2    2.307391  2.307391  2.307391   4.409336              2.307391   
3    0.736775  0.736775  0.736775   1.407949              0.736775   
4    2.328350  2.328350  2.328350   4.449388              2.328350   
5    2.300307  2.300307  2.300307   4.395800              2.300307   
6    1.060287  1.060287  1.060287   2.026167              1.060287   
7    2.338375  2.338375  2.338375   4.468545              2.338375   
8    2.452888  2.452888  2.452888   4.687375              2.452888   
9    2.450796  2.450796  2.450796   4.683378              2.450796   
10   1.440494  1.440494  1.440494   2.752729              1.440494   
11   2.393833  2.393833  2.393833   4.574523              2.393833   
12   0.652011  0.652011  0.652011   1.245968              0.652011   
13   1.588463  1.588463  1.588463   3.035492              1.588463   
14   1.037152  1.037152  1.037152   1.981958              1.037152   
15   1.046768  1.046768  1.046768   2.000334              1.046768   
16   1.563126  1.563126  1.563126   2.987074              1.563126   
17   0.735779  0.735779  0.735779   1.406046              0.735779   
18   1.329473  1.329473  1.329473   2.540572              1.329473   
19   0.696629  0.696629  0.696629   1.331231              0.696629   
20   2.458533  2.458533  2.458533   4.698163              2.458533   
21   2.435047  2.435047  2.435047   4.653281              2.435047   
22   2.308840  2.308840  2.308840   4.412106              2.308840   
23   0.813112  0.813112  0.813112   1.553826              0.813112   
24   2.435781  2.435781  2.435781   4.654685              2.435781   
25   2.211490  2.211490  2.211490   4.226073              2.211490   
26   2.372678  2.372678  2.372678   4.534098              2.372678   
27   2.462374  2.462374  2.462374   4.705503              2.462374   
28   2.422056  2.422056  2.422056   4.628456              2.422056   
29   0.700271  0.700271  0.700271   1.338191              0.700271   
..        ...       ...       ...        ...                   ...   
654  2.466817  2.466817  2.466817   4.713993              2.466817   
655  2.461371  2.461371  2.461371   4.703586              2.461371   
656  1.473193  1.473193  1.473193   2.815216              1.473193   
657  2.465361  2.465361  2.465361   4.711210              2.465361   
658  1.073965  1.073965  1.073965   2.052307              1.073965   
659  1.446478  1.446478  1.446478   2.764163              1.446478   
660  1.075915  1.075915  1.075915   2.056033              1.075915   
661  0.946440  0.946440  0.946440   1.808611              0.946440   
662  2.075026  2.075026  2.075026   3.965296              2.075026   
663  0.708327  0.708327  0.708327   1.353585              0.708327   
664  0.865949  0.865949  0.865949   1.654795              0.865949   
665  0.678616  0.678616  0.678616   1.296810              0.678616   
666  2.471002  2.471002  2.471002   4.721990              2.471002   
667  2.428046  2.428046  2.428046   4.639903              2.428046   
668  2.293205  2.293205  2.293205   4.382226              2.293205   
669  0.744066  0.744066  0.744066   1.421882              0.744066   
670  2.457976  2.457976  2.457976   4.697099              2.457976   
671  2.307601  2.307601  2.307601   4.409737              2.307601   
672  2.332200  2.332200  2.332200   4.456744              2.332200   
673  2.464187  2.464187  2.464187   4.708968              2.464187   
674  2.426140  2.426140  2.426140   4.636261              2.426140   
675  1.398135  1.398135  1.398135   2.671782              1.398135   
676  2.461717  2.461717  2.461717   4.704247              2.461717   
677  2.428182  2.428182  2.428182   4.640163              2.428182   
678  2.454028  2.454028  2.454028   4.689553              2.454028   
679  2.305174  

## FMS price and cost parameters

In [8]:
mea2_cnn.execute("drop table pricecost_fms")

In [9]:
filename = '%s/ForestManagementAssumptions.xls' % (update_path, )
df = pd.read_excel(filename, sheet_name='pricecost').drop(columns='region')

In [10]:
df = df.sort_values(by=['assumption_id', 'tsa_num'])

In [11]:
df.to_sql('pricecost_fms', mea2_cnn, if_exists='replace', index=False)

In [12]:
df = pd.read_sql_query('select * from pricecost_fms', mea2_cnn)
df

assumption_id  tsa_num  SWLogPrice  HWLogPrice  SalvageLogPrice  \
0                1        1   74.877407   64.877407        36.406956   
1                1        2   74.877407   64.877407        36.406956   
2                1        3   74.877407   64.877407        36.406956   
3                1        4   74.877407   64.877407        36.406956   
4                1        5   74.877407   64.877407        36.406956   
5                1        7   74.877407   64.877407        36.406956   
6                1        8   74.877407   64.877407        36.406956   
7                1        9   74.877407   64.877407        36.406956   
8                1       10   74.877407   64.877407        36.406956   
9                1       11   74.877407   64.877407        36.406956   
10               1       12   74.877407   64.877407        36.406956   
11               1       13   74.877407   64.877407        36.406956   
12               1       14   74.877407   64.877407        36.406956   
13               1       15   74.877407   64.877407        36.406956   
14               1       16   74.877407   64.877407        36.406956   
15               1       17   74.877407   64.877407        36.406956   
16               1       18   74.877407   64.877407        36.406956   
17               1       19  112.932390  102.932390        61.723265   
18               1       20   74.877407   64.877407        36.406956   
19               1       21  112.932390  102.932390        61.723265   
20               1       22   74.877407   64.877407        36.406956   
21               1       23   74.877407   64.877407        36.406956   
22               1       24   74.877407   64.877407        36.406956   
23               1       25  112.932390  102.932390        61.723265   
24               1       26   74.877407   64.877407        36.406956   
25               1       27   74.877407   64.877407        36.406956   
26               1       29   74.877407   64.877407        36.406956   
27               1       30  112.932390  102.932390        61.723265   
28               1       31  112.932390  102.932390        61.723265   
29               1       33  112.932390  102.932390        61.723265   
..             ...      ...         ...         ...              ...   
464             13       10   74.342555   64.342555        36.406956   
465             13       11   74.416037   64.416037        36.406956   
466             13       12   74.342555   64.342555        36.406956   
467             13       13   74.416037   64.416037        36.406956   
468             13       14   74.342555   64.342555        36.406956   
469             13       15   74.416037   64.416037        36.406956   
470             13       16   74.342555   64.342555        36.406956   
471             13       17   74.416037   64.416037        36.406956   
472             13       18   74.416037   64.416037        36.406956   
473             13       19  104.253406   94.253406        61.723265   
474             13       20   74.342555   64.342555        36.406956   
475             13       21  104.253406   94.253406        61.723265   
476             13       22   74.416037   64.416037        36.406956   
477             13       23   74.416037   64.416037        36.406956   
478             13       24   74.342555   64.342555        36.406956   
479             13       25  104.253406   94.253406        61.723265   
480             13       26   74.416037   64.416037        36.406956   
481             13       27   74.416037   64.416037        36.406956   
482             13       29   74.416037   64.416037        36.406956   
483             13       30  104.253406   94.253406        61.723265   
484             13       31  104.253406   94.253406        61.723265   
485             13       33  104.253406   94.253406        61.723265   
486             13       37  104.253406   94.253406        61.723265   
487             13       38  104.253406   94.

## HWP price and cost parameters

In [13]:
mea2_cnn.execute("drop table pricecost_hwp")

In [14]:
filename = '%s/HarvestedWoodProductAssumptions.xls' % (update_path, )
df = pd.read_excel(filename, sheet_name='pricecost').drop(columns='region')

In [15]:
df = df.sort_values(by=['assumption_id', 'tsa_num'])

In [16]:
df.to_sql('pricecost_hwp', mea2_cnn, if_exists='replace', index=False)

In [17]:
df = pd.read_sql_query('select * from pricecost_hwp', mea2_cnn)
df

assumption_id  tsa_num  SawnwoodPrice  PanelPrice  OtherIRPrice  \
0                 1        1      79.962581  196.122554     79.962581   
1                 1        2      79.962581  196.122554     79.962581   
2                 1        3      79.962581  196.122554     79.962581   
3                 1        4      79.962581  196.122554     79.962581   
4                 1        5      79.962581  196.122554     79.962581   
5                 1        7      79.962581  196.122554     79.962581   
6                 1        8      79.962581  196.122554     79.962581   
7                 1        9      79.962581  196.122554     79.962581   
8                 1       10      79.962581  196.122554     79.962581   
9                 1       11      79.962581  196.122554     79.962581   
10                1       12      79.962581  196.122554     79.962581   
11                1       13      79.962581  196.122554     79.962581   
12                1       14      79.962581  196.122554     79.962581   
13                1       15      79.962581  196.122554     79.962581   
14                1       16      79.962581  196.122554     79.962581   
15                1       17      79.962581  196.122554     79.962581   
16                1       18      79.962581  196.122554     79.962581   
17                1       19      79.962581  196.122554     79.962581   
18                1       20      79.962581  196.122554     79.962581   
19                1       21      79.962581  196.122554     79.962581   
20                1       22      79.962581  196.122554     79.962581   
21                1       23      79.962581  196.122554     79.962581   
22                1       24      79.962581  196.122554     79.962581   
23                1       25      79.962581  196.122554     79.962581   
24                1       26      79.962581  196.122554     79.962581   
25                1       27      79.962581  196.122554     79.962581   
26                1       29      79.962581  196.122554     79.962581   
27                1       30      79.962581  196.122554     79.962581   
28                1       31      79.962581  196.122554     79.962581   
29                1       33      79.962581  196.122554     79.962581   
...             ...      ...            ...         ...           ...   
1680             45       10      79.962581  196.122554     79.962581   
1681             45       11      79.962581  196.122554     79.962581   
1682             45       12      79.962581  196.122554     79.962581   
1683             45       13      79.962581  196.122554     79.962581   
1684             45       14      79.962581  196.122554     79.962581   
1685             45       15      79.962581  196.122554     79.962581   
1686             45       16      79.962581  196.122554     79.962581   
1687             45       17      79.962581  196.122554     79.962581   
1688             45       18      79.962581  196.122554     79.962581   
1689             45       19      79.962581  196.122554     79.962581   
1690             45       20      79.962581  196.122554     79.962581   
1691             45       21      79.962581  196.122554     79.962581   
1692             45       22      79.962581  196.122554     79.962581   
1693             45       23      79.962581  196.122554     79.962581   
1694             45       24      79.962581  196.122554     79.962581   
1695             45       25      79.962581  196.122554     79.962581   
1696             45       26      79.962581  196.122554     79.962581   
1697             45       27      79.962581  196.122554     79.962581   
1698             45       29      79.962581  196.122554     79.962581   
1699             45       30      79.962581  196.122554     79.962581   
1700             45       31      79.962581  196.122554     79.962581   
1701             45       33      79.962581  196.122554     79.962581   
1702             45       37      79.962581  196.122554     79.9

## Displacement price and cost parameters

In [18]:
mea2_cnn.execute("drop table pricecost_dis")

In [19]:
filename = '%s/DisplacementAssumptions.xls' % (update_path, )
df = pd.read_excel(filename, sheet_name='pricecost')

In [20]:
df = df.sort_values(by=['assumption_id', 'tsa_num'])

In [21]:
df.to_sql('pricecost_dis', mea2_cnn, if_exists='replace', index=False)

In [22]:
df = pd.read_sql_query('select * from pricecost_dis', mea2_cnn)
df

assumption_id  tsa_num  ConcretePrice  PlasticPrice  EnergyPrice  \
0                0        1       0.000000      0.000000     0.000000   
1                0        2       0.000000      0.000000     0.000000   
2                0        3       0.000000      0.000000     0.000000   
3                0        4       0.000000      0.000000     0.000000   
4                0        5       0.000000      0.000000     0.000000   
5                0        7       0.000000      0.000000     0.000000   
6                0        8       0.000000      0.000000     0.000000   
7                0        9       0.000000      0.000000     0.000000   
8                0       10       0.000000      0.000000     0.000000   
9                0       11       0.000000      0.000000     0.000000   
10               0       12       0.000000      0.000000     0.000000   
11               0       13       0.000000      0.000000     0.000000   
12               0       14       0.000000      0.000000     0.000000   
13               0       15       0.000000      0.000000     0.000000   
14               0       16       0.000000      0.000000     0.000000   
15               0       17       0.000000      0.000000     0.000000   
16               0       18       0.000000      0.000000     0.000000   
17               0       19       0.000000      0.000000     0.000000   
18               0       20       0.000000      0.000000     0.000000   
19               0       21       0.000000      0.000000     0.000000   
20               0       22       0.000000      0.000000     0.000000   
21               0       23       0.000000      0.000000     0.000000   
22               0       24       0.000000      0.000000     0.000000   
23               0       25       0.000000      0.000000     0.000000   
24               0       26       0.000000      0.000000     0.000000   
25               0       27       0.000000      0.000000     0.000000   
26               0       29       0.000000      0.000000     0.000000   
27               0       30       0.000000      0.000000     0.000000   
28               0       31       0.000000      0.000000     0.000000   
29               0       33       0.000000      0.000000     0.000000   
..             ...      ...            ...           ...          ...   
464             12       10      75.148127   1988.802164    34.031612   
465             12       11      75.148127   1988.802164    33.393485   
466             12       12      75.148127   1988.802164    71.370797   
467             12       13      75.148127   1988.802164    33.403501   
468             12       14      75.148127   1988.802164    72.080336   
469             12       15      75.148127   1988.802164    69.300105   
470             12       16      75.148127   1988.802164    71.528665   
471             12       17      75.148127   1988.802164    67.824565   
472             12       18      75.148127   1988.802164    67.639070   
473             12       19      75.148127   1988.802164    71.811526   
474             12       20      75.148127   1988.802164    71.484286   
475             12       21      75.148127   1988.802164    69.535706   
476             12       22      75.148127   1988.802164    33.389466   
477             12       23      75.148127   1988.802164    39.333641   
478             12       24      75.148127   1988.802164    63.492514   
479             12       25      75.148127   1988.802164    71.688738   
480             12       26      75.148127   1988.802164    59.303146   
481             12       27      75.148127   1988.802164    52.743326   
482             12       29      75.148127   1988.802164    52.757812   
483             12       30      75.148127   1988.802164    33.414632   
484             12       31      75.148127   1988.802164    33.512979   
485             12       33      75.148127   1988.802164    71.994222   
486             12       37      75.148127   1988.802164    33.

# Compile 9 suite-wise `mea_params` databases

In [23]:
# suite_names = {'default_base':'default_base_future_aggregated_results',
#                'default_clean':'default_clean_future_aggregated_results',
#                'default_wood_buildings':'default_wood_buildings_future_aggregated_results',
#                'hi_base':'hi_base_future_aggregated_results',
#                'hi_clean':'hi_clean_future_aggregated_results',
#                'hi_wood_buildings':'hi_wood_buildings_future_aggregated_results',
#                'lo_base':'lo_base_future_aggregated_results',
#                'lo_clean':'lo_clean_future_aggregated_results',
#                'lo_wood_buildings':'lo_wood_buildings_future_aggregated_results'}

In [24]:
import numpy as np
import mea

basenames = [int(x[-2:]) for x in mea.read_basenames('../dat/basenames.txt')]
scenarios = ['CBM_Base_HWP_Base',
             'CBM_Base_HWP_LLP',
             'CBM_A_HWP_Base',
             'CBM_A_HWP_LLP',
             'CBM_B_HWP_Base',
             'CBM_B_HWP_LLP',
             'CBM_C_HWP_Base',
             'CBM_C_HWP_LLP',
             'CBM_D_HWP_Base',
             'CBM_D_HWP_LLP',
             'CBM_OG_HWP_Base',
             'CBM_OG_HWP_LLP']
prodconv_index = pd.MultiIndex.from_product([scenarios, basenames], names=['scenario', 'tsa_num'])
prodconv_columns = ['tsa_num', 'sawnwood', 'panels', 'otherirw', 'pulppaper', 'bioenergycommodities',
                    'bioenergyharvest', 'bioenergyharvestresidue', 'bioenergymillresidue']
#df_prodconv = pd.DataFrame(index=prodconv_index, columns=prodconv_columns).fillna(0.)
df_prodconv = pd.DataFrame(index=prodconv_index)

## `default_base`

In [25]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-default_base.db

In [26]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-default_base.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 2, 3, 4, 5, 6]]
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 1, 2]]
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 1, 2
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


# `default_clean`

In [27]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-default_clean.db

In [28]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-default_clean.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 2, 3, 4, 5, 6]]
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 2, 3, 34, 35, 6, 7, 8, 9, 36, 37, 12]]
df.rename(index={34:4, 35:5, 36:10, 37:11}, inplace=True)
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 3, 4]]
df.rename(index={3:1, 4:2}, inplace=True)
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 3, 4
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


# `default_woodbuildings`

In [29]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-default_woodbuildings.db

In [30]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-default_woodbuildings.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 2, 3, 4, 5, 6]]
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 1, 2]]
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 5, 6
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


# `lo_base`

In [31]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-lo_base.db

In [32]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-lo_base.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 7, 8, 4, 9, 10]]
df.rename(index={7:2, 8:3, 9:5, 10:6}, inplace=True)
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]
df.rename(index={13:2, 14:3, 15:4, 16:5, 17:6, 18:7, 19:8, 20:9, 21:10, 22:11, 23:12}, inplace=True)
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 5, 6]]
df.rename(index={5:1, 6:2}, inplace=True)
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 7, 8
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


# `lo_clean`

In [33]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-lo_clean.db

In [34]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-lo_clean.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 7, 8, 4, 9, 10]]
df.rename(index={7:2, 8:3, 9:5, 10:6}, inplace=True)
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 13, 14, 38, 39, 17, 18, 19, 20, 40, 41, 23]]
df.rename(index={13:2, 14:3, 38:4, 39:5, 17:6, 18:7, 19:8, 20:9, 40:10, 41:11, 23:12}, inplace=True)
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 7, 8]]
df.rename(index={7:1, 8:2}, inplace=True)
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 9, 10
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


# `lo_woodbuildings`

In [35]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-lo_woodbuildings.db

In [36]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-lo_woodbuildings.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 7, 8, 4, 9, 10]]
df.rename(index={7:2, 8:3, 9:5, 10:6}, inplace=True)
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]
df.rename(index={13:2, 14:3, 15:4, 16:5, 17:6, 18:7, 19:8, 20:9, 21:10, 22:11, 23:12}, inplace=True)
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 5, 6]]
df.rename(index={5:1, 6:2}, inplace=True)
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 11, 12
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


# `hi_base`

In [37]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-hi_base.db

In [38]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-hi_base.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 11, 3, 4, 12, 13]]
df.rename(index={11:2, 12:5, 13:6}, inplace=True)
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 24, 3, 25, 26, 27, 28, 29, 30, 31, 32, 33]]
df.rename(index={24:2, 25:4, 26:5, 27:6, 28:7, 29:8, 30:9, 31:10, 32:11, 33:12}, inplace=True)
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 9, 10]]
df.rename(index={9:1, 10:2}, inplace=True)
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 13, 14
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


# `hi_clean`

In [39]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-hi_clean.db

In [40]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-hi_clean.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 11, 3, 4, 12, 13]]
df.rename(index={11:2, 12:5, 13:6}, inplace=True)
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 24, 3, 42, 43, 27, 28, 29, 30, 44, 45, 33]]
df.rename(index={24:2, 42:4, 43:5, 27:6, 28:7, 29:8, 30:9, 44:10, 45:11, 33:12}, inplace=True)
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 11, 12]]
df.rename(index={11:1, 12:2}, inplace=True)
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 15, 16
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


# `hi_woodbuildings`

In [41]:
! cp ../dat/mea_params/mea_params.db ../dat/mea_params/mea_params-hi_woodbuildings.db

In [42]:
cnn = sqlite3.connect('../dat/mea_params/mea_params-hi_woodbuildings.db')

# fms
df = pd.read_sql_query('select * from pricecost_fms', cnn).set_index('assumption_id')
df = df.loc[[1, 11, 3, 4, 12, 13]]
df.rename(index={11:2, 12:5, 13:6}, inplace=True)
df.to_sql('pricecost_fms', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# hwp
df = pd.read_sql_query('select * from pricecost_hwp', cnn).set_index('assumption_id')
df = df.loc[[1, 24, 3, 25, 26, 27, 28, 29, 30, 31, 32, 33]]
df.rename(index={24:2, 25:4, 26:5, 27:6, 28:7, 29:8, 30:9, 31:10, 32:11, 33:12}, inplace=True)
df.to_sql('pricecost_hwp', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# dis
df = pd.read_sql_query('select * from pricecost_dis', cnn).set_index('assumption_id')
df = df.loc[[0, 9, 10]]
df.rename(index={9:1, 10:2}, inplace=True)
df.to_sql('pricecost_dis', cnn, if_exists='replace', index=True)
print(np.unique(df.index.values))

# prodconv
a1, a2 = 17, 18
_df = pd.read_sql_query('select * from prodconv', cnn).set_index('assumption_id').reindex(columns=prodconv_columns)
df = df_prodconv.copy().reset_index().set_index('scenario')
df = df.join(_df.loc[a1].set_index('tsa_num'), on='tsa_num')
df.loc['CBM_Base_HWP_Base', 1:] = 0.
df.loc['CBM_Base_HWP_LLP', 1:] = 0.
df.loc['CBM_A_HWP_Base', 1:] = 0.
df.loc['CBM_A_HWP_LLP', 1:] = 0.
df.loc['CBM_B_HWP_Base', 1:] = 0.
df.loc['CBM_B_HWP_LLP', 1:] = 0.
#df.loc['CBM_C_HWP_Base', :] = 0.
#df.loc['CBM_C_HWP_LLP', :] = 0.
df.loc['CBM_D_HWP_Base', :] = _df.loc[a2].values
df.loc['CBM_D_HWP_LLP', :] = _df.loc[a2].values
df.loc['CBM_OG_HWP_Base', 1:] = 0.
df.loc['CBM_OG_HWP_LLP', 1:] = 0.
df['tsa_num'] = df.tsa_num.astype('int')
df.to_sql('prodconv', cnn, if_exists='replace', index=True)

cnn.close()

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[0 1 2]


Everything below here is "junk" (i.e., from previous stages in phase2 developement process).

# Compile parameters for phase 2 MEA _validation_

In [43]:
mea2_db_path = '../dat/validate/mea_validate.db'
mea2_cnn = sqlite3.connect(mea2_db_path)
#c = mea2_cnn.cursor()

In [ ]:
for tn1, tn2, idc in tblnames['pricecost']:
    df = mea1_db[tn1].to_data_frame()
    df['SPUID'] = df['SPUID'].astype(str)
    df = df.rename(columns={'SPUID':'tsa_num', idc:'assumption_id'})
    df.to_sql(tn2, mea2_cnn, if_exists='replace', index=False)

In [ ]:
tn1, tn2 = tblnames['prodconv']
colmap = {'SPUID':'tsa_num', 
          'Sawnwood':'sawnwood',
          'Panel':'panels',
          'OtherIRW':'otherirw',
          'PulpPaper':'pulppaper',
          'BioenergyCommodities':'bioenergycommodities',
          'BioenergyHarvest':'bioenergyharvest',
          'BioenergyHarvestResidue':'bioenergyharvestresidue',
          'BioenergyMillResidue':'bioenergymillresidue'}
df = mea1_db[tn1].to_data_frame() # use RunID 1 for base scenario, 10 for alt scenario
df = df.query("RunID in [1, 10]").set_index('RunID')
df.loc[1, 'scenario'] = 'CBM_Base_HWP_Base'
df.loc[10, 'scenario'] = 'CBM_D_HWP_LLP'
df = df.reset_index().drop(columns='RunID').rename(columns=colmap)
df.to_sql(tn2, mea2_cnn, if_exists='replace', index=False)

In [ ]:
df

In [6]:
mea2_cnn.close()

# Compile parameters for phase 2 _development_

In [1]:
import sqlite3
import pandas as pd
import mdbread

In [5]:
mea1_db_path = '../dat/mea_fcm/model1/MEAInputDB_Theme1_V6.mdb'
mea1_db = mdbread.MDB(mea1_db_path)
tblnames = {'pricecost':[('tblFMSPriceCostData', 'pricecost_fms', 'FMSCostAssumptionID'), 
                         ('tblHWPPriceCostData', 'pricecost_hwp', 'HWPCostAssumptionID'), 
                         ('tblDisPriceCostData', 'pricecost_dis', 'DisCostAssumptionID')],
            'prodconv':('tblProductionConversionParameters', 'prodconv')}

In [6]:
mea2_db_path = '../dat/mea.db'
mea2_cnn = sqlite3.connect(mea2_db_path)

The following block of code imports price and cost data from the phase 1 MEA database. *Use this data for development purposes only!* Replace with updated data when available (see Zach Xu).

We need to fake `tsa_num` values. So, we select the first 38 `SPUID` values from the old database and replace them with the 38 `tsa_num` values, plus rename `SPUID` column to `tsa_num`. 

In [7]:
def read_basenames(path):
    return [line.lower().strip().split(' ')[0] 
            for line in open(path, 'r') if not line.startswith('#')]

basenames = [float(x[-2:]) for x in read_basenames('../dat/basenames.txt')]

for tn1, tn2, idc in tblnames['pricecost']:
    df = mea1_db[tn1].to_data_frame()
    spuids = [str(x) for x in df['SPUID'].unique()[:len(basenames)]]
    s = "SPUID in [%s]" % ','.join(spuids)
    df = df.query(s)
    df['SPUID'] = df['SPUID'].astype(str)
    df = df.replace(spuids, basenames).rename(columns={'SPUID':'tsa_num', idc:'assumption_id'})
    df.to_sql(tn2, mea2_cnn, if_exists='replace', index=False)

In [8]:
#mea2_cnn.close()